// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\animated_models\foliage_cod5_tree_jungle_02::main();
	maps\animated_models\foliage_pacific_bushtree01::main();
}
