// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\animated_models\foliage_pacific_bushtree01::main();
	maps\animated_models\foliage_pacific_bushtree02::main();
	maps\animated_models\foliage_tree_palm_bushy_1::main();
}
